//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleSFTPSync
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileID { get; set; }
        public int ConnectionID { get; set; }
        public string RemotePath { get; set; }
        public long Length { get; set; }
        public System.DateTime DateDiscovered { get; set; }
        public Nullable<System.DateTime> DateDownloaded { get; set; }
        public System.DateTime RemoteDateModified { get; set; }
    }
}
